-- THIS SCRIPTS ARE MANDATORY FOR PROPERLY WORK OF ASSESSMENT PLUGIN

-- REGISTRIES FOR EPERSONGROUP TABLE

-- GROUP FOR EXPERT USERS
INSERT INTO EPERSONGROUP (EPERSON_GROUP_ID)
VALUES (2);

-- GROUP FOR STUDENT USERS
INSERT INTO EPERSONGROUP (EPERSON_GROUP_ID)
VALUES (3);

-- Registries for Layer Table

INSERT INTO LAYER (LAYER_NAME) 
VALUES ('Administrator');

INSERT INTO LAYER (LAYER_NAME) 
VALUES ('Expert');

INSERT INTO LAYER (LAYER_NAME) 
VALUES ('Student');

-- Registries for Dimension Table

INSERT INTO DIMENSION (DIMENSION_NAME) 
VALUES ('Content');

INSERT INTO DIMENSION (DIMENSION_NAME) 
VALUES ('Contextual');

INSERT INTO DIMENSION (DIMENSION_NAME) 
VALUES ('Educational');

INSERT INTO DIMENSION (DIMENSION_NAME) 
VALUES ('Esthetic');

INSERT INTO DIMENSION (DIMENSION_NAME) 
VALUES ('Functional');

INSERT INTO DIMENSION (DIMENSION_NAME) 
VALUES ('Metadata');

-- Regitries for Criteria Table

INSERT INTO CRITERIA (CRITERIA_NAME) 
VALUES ('Accessibility');

INSERT INTO CRITERIA (CRITERIA_NAME) 
VALUES ('Accuracy');

INSERT INTO CRITERIA (CRITERIA_NAME) 
VALUES ('Availability');

INSERT INTO CRITERIA (CRITERIA_NAME) 
VALUES ('Coherence');

INSERT INTO CRITERIA (CRITERIA_NAME) 
VALUES ('Completeness');

INSERT INTO CRITERIA (CRITERIA_NAME) 
VALUES ('Consistency');

INSERT INTO CRITERIA (CRITERIA_NAME) 
VALUES ('Ease to use');

INSERT INTO CRITERIA (CRITERIA_NAME) 
VALUES ('Effectiveness');

INSERT INTO CRITERIA (CRITERIA_NAME) 
VALUES ('Motivation');

INSERT INTO CRITERIA (CRITERIA_NAME) 
VALUES ('Potential Effectiveness');

INSERT INTO CRITERIA (CRITERIA_NAME) 
VALUES ('Relevance');

INSERT INTO CRITERIA (CRITERIA_NAME) 
VALUES ('Reusability');

INSERT INTO CRITERIA (CRITERIA_NAME) 
VALUES ('Rigor and Relevance');

INSERT INTO CRITERIA (CRITERIA_NAME) 
VALUES ('Visibility');

INSERT INTO CRITERIA (CRITERIA_NAME) 
VALUES ('Visual Design');

--Registries for Layer2Dimension table

INSERT INTO LAYER2DIMENSION (DIMENSION_ID,LAYER_ID)
SELECT D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D
WHERE D.DIMENSION_NAME='Functional'
AND L.LAYER_NAME='Administrator';

INSERT INTO LAYER2DIMENSION (DIMENSION_ID,LAYER_ID)
SELECT D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D
WHERE D.DIMENSION_NAME='Metadata'
AND L.LAYER_NAME='Administrator';

INSERT INTO LAYER2DIMENSION (DIMENSION_ID,LAYER_ID)
SELECT D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D
WHERE D.DIMENSION_NAME='Contextual'
AND L.LAYER_NAME='Administrator';

INSERT INTO LAYER2DIMENSION (DIMENSION_ID,LAYER_ID)
SELECT D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D
WHERE D.DIMENSION_NAME='Content'
AND L.LAYER_NAME='Expert';

INSERT INTO LAYER2DIMENSION (DIMENSION_ID,LAYER_ID)
SELECT D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D
WHERE D.DIMENSION_NAME='Educational'
AND L.LAYER_NAME='Expert';

INSERT INTO LAYER2DIMENSION (DIMENSION_ID,LAYER_ID)
SELECT D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D
WHERE D.DIMENSION_NAME='Esthetic'
AND L.LAYER_NAME='Expert';

INSERT INTO LAYER2DIMENSION (DIMENSION_ID,LAYER_ID)
SELECT D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D
WHERE D.DIMENSION_NAME='Functional'
AND L.LAYER_NAME='Expert';

INSERT INTO LAYER2DIMENSION (DIMENSION_ID,LAYER_ID)
SELECT D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D
WHERE D.DIMENSION_NAME='Metadata'
AND L.LAYER_NAME='Expert';

INSERT INTO LAYER2DIMENSION (DIMENSION_ID,LAYER_ID)
SELECT D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D
WHERE D.DIMENSION_NAME='Contextual'
AND L.LAYER_NAME='Student';

INSERT INTO LAYER2DIMENSION (DIMENSION_ID,LAYER_ID)
SELECT D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D
WHERE D.DIMENSION_NAME='Educational'
AND L.LAYER_NAME='Student';

INSERT INTO LAYER2DIMENSION (DIMENSION_ID,LAYER_ID)
SELECT D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D
WHERE D.DIMENSION_NAME='Esthetic'
AND L.LAYER_NAME='Student';

INSERT INTO LAYER2DIMENSION (DIMENSION_ID,LAYER_ID)
SELECT D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D
WHERE D.DIMENSION_NAME='Functional'
AND L.LAYER_NAME='Student';

INSERT INTO LAYER2DIMENSION (DIMENSION_ID,LAYER_ID)
SELECT D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D
WHERE D.DIMENSION_NAME='Metadata'
AND L.LAYER_NAME='Student';

--Registries for Assessment-Metric table

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Reusability' 
AND D.DIMENSION_NAME='Functional'
AND L.LAYER_NAME='Administrator';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Availability' 
AND D.DIMENSION_NAME='Functional'
AND L.LAYER_NAME='Administrator';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Completeness' 
AND D.DIMENSION_NAME='Metadata'
AND L.LAYER_NAME='Administrator';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Consistency' 
AND D.DIMENSION_NAME='Metadata'
AND L.LAYER_NAME='Administrator';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Coherence' 
AND D.DIMENSION_NAME='Metadata'
AND L.LAYER_NAME='Administrator';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Visibility' 
AND D.DIMENSION_NAME='Contextual'
AND L.LAYER_NAME='Administrator';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Rigor and Relevance' 
AND D.DIMENSION_NAME='Content'
AND L.LAYER_NAME='Expert';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Potential Effectiveness' 
AND D.DIMENSION_NAME='Educational'
AND L.LAYER_NAME='Expert';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Visual Design' 
AND D.DIMENSION_NAME='Esthetic'
AND L.LAYER_NAME='Expert';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Reusability' 
AND D.DIMENSION_NAME='Functional'
AND L.LAYER_NAME='Expert';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Ease to use' 
AND D.DIMENSION_NAME='Functional'
AND L.LAYER_NAME='Expert';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Accessibility' 
AND D.DIMENSION_NAME='Functional'
AND L.LAYER_NAME='Expert';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Completeness' 
AND D.DIMENSION_NAME='Metadata'
AND L.LAYER_NAME='Expert';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Accuracy' 
AND D.DIMENSION_NAME='Metadata'
AND L.LAYER_NAME='Expert';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Relevance' 
AND D.DIMENSION_NAME='Contextual'
AND L.LAYER_NAME='Student';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Motivation' 
AND D.DIMENSION_NAME='Educational'
AND L.LAYER_NAME='Student';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Effectiveness' 
AND D.DIMENSION_NAME='Educational'
AND L.LAYER_NAME='Student';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Visual Design' 
AND D.DIMENSION_NAME='Esthetic'
AND L.LAYER_NAME='Student';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Availability' 
AND D.DIMENSION_NAME='Functional'
AND L.LAYER_NAME='Student';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Ease to use' 
AND D.DIMENSION_NAME='Functional'
AND L.LAYER_NAME='Student';

INSERT INTO ASSESSMENT_METRIC (CRITERIA_ID,DIMENSION_ID,LAYER_ID)
SELECT C.CRITERIA_ID,D.DIMENSION_ID,L.LAYER_ID 
FROM LAYER L,DIMENSION D,CRITERIA C
WHERE C.CRITERIA_NAME='Accuracy' 
AND D.DIMENSION_NAME='Metadata'
AND L.LAYER_NAME='Student';


COMMIT;



