--Drop tables
DROP TABLE ASSESSMENT_HISTORY CASCADE;
DROP TABLE ASSESSMENT_METRIC CASCADE;
DROP TABLE ASSESSMENT_RESULT CASCADE;
DROP TABLE CRITERIA CASCADE;
DROP TABLE DIMENSION CASCADE;
DROP TABLE DIMENSION_WEIGHTING CASCADE;
DROP TABLE LAYER CASCADE;
DROP TABLE LAYER2DIMENSION CASCADE;

--Drop sequences
DROP SEQUENCE assessment_history_seq;
DROP SEQUENCE assessment_metric_seq;
DROP SEQUENCE assessment_result_seq;
DROP SEQUENCE criteria_seq;
DROP SEQUENCE dimension_seq;
DROP SEQUENCE dimension_weighting_seq;
DROP SEQUENCE layer_seq;


CREATE SEQUENCE assessment_history_seq INCREMENT 1 START 1;

CREATE TABLE ASSESSMENT_HISTORY ( 
	ASSESSMENT_HISTORY_ID integer DEFAULT nextval(('assessment_history_seq'::text)::regclass) NOT NULL,
	ASSESSMENT_RESULT_ID integer,
	EPERSON_ID integer,
	ASSESS_VALUE varchar(30) 
);

CREATE SEQUENCE assessment_metric_seq INCREMENT 1 START 1;

CREATE TABLE ASSESSMENT_METRIC ( 
	ASSESSMENT_METRIC_ID integer DEFAULT nextval(('assessment_metric_seq'::text)::regclass) NOT NULL,
	CRITERIA_ID integer,
	DIMENSION_ID integer,
	LAYER_ID integer
);

CREATE SEQUENCE assessment_result_seq INCREMENT 1 START 1;

CREATE TABLE ASSESSMENT_RESULT ( 
	ASSESSMENT_RESULT_ID integer DEFAULT nextval(('assessment_result_seq'::text)::regclass) NOT NULL,
	ASSESSMENT_METRIC_ID integer,
	ITEM_ID integer,
	METRIC_VALUE varchar(30)
);

CREATE SEQUENCE criteria_seq INCREMENT 1 START 1;

CREATE TABLE CRITERIA ( 
	CRITERIA_ID integer DEFAULT nextval(('criteria_seq'::text)::regclass) NOT NULL,
	CRITERIA_NAME varchar(50)
);

CREATE SEQUENCE dimension_seq INCREMENT 1 START 1;

CREATE TABLE DIMENSION ( 
	DIMENSION_ID integer DEFAULT nextval(('dimension_seq'::text)::regclass) NOT NULL,
	DIMENSION_NAME varchar(50)
);

CREATE SEQUENCE dimension_weighting_seq INCREMENT 1 START 1;

CREATE TABLE DIMENSION_WEIGHTING ( 
	DIMENSION_WEIGHTING_ID integer DEFAULT nextval(('dimension_weighting_seq'::text)::regclass) NOT NULL,
	DIMENSION_ID integer,
	LAYER_ID integer,
	ITEM_ID integer,
	ADMIN_WEIGHT varchar(30),
	EXPERT_WEIGHT integer
);

CREATE SEQUENCE layer_seq INCREMENT 1 START 1
;

CREATE TABLE LAYER ( 
	LAYER_ID integer DEFAULT nextval(('layer_seq'::text)::regclass) NOT NULL,
	LAYER_NAME varchar(50) NOT NULL
)
;

CREATE TABLE LAYER2DIMENSION ( 
	DIMENSION_ID integer NOT NULL,
	LAYER_ID integer NOT NULL
)
;

--constraints
ALTER TABLE ASSESSMENT_HISTORY
	ADD CONSTRAINT UQ_ASSESSMENT_HIST_EPERSON UNIQUE (ASSESSMENT_RESULT_ID, EPERSON_ID);

ALTER TABLE ASSESSMENT_RESULT
	ADD CONSTRAINT UQ_ASSESSMENT_RESULT_BY_ITEM UNIQUE (ASSESSMENT_METRIC_ID, ITEM_ID)
;
ALTER TABLE CRITERIA
	ADD CONSTRAINT UQ_CRITERIA_CRITERIA_NAME UNIQUE (CRITERIA_NAME)
;
ALTER TABLE DIMENSION
	ADD CONSTRAINT UQ_DIMENSION_DIMENSION_NAME UNIQUE (DIMENSION_NAME)
;
ALTER TABLE DIMENSION_WEIGHTING
	ADD CONSTRAINT UQ_DIMENSION_WEIGHTING_BY_ITEM UNIQUE (DIMENSION_ID, LAYER_ID, ITEM_ID)
;
ALTER TABLE LAYER
	ADD CONSTRAINT UQ_LAYER_LAYER_NAME UNIQUE (LAYER_NAME)
;
	
--primary keys
ALTER TABLE ASSESSMENT_HISTORY ADD CONSTRAINT PK_ASSESSMENT_HISTORY 
	PRIMARY KEY (ASSESSMENT_HISTORY_ID)
;
ALTER TABLE ASSESSMENT_METRIC ADD CONSTRAINT PK_ASSESSMENT_METRIC 
	PRIMARY KEY (ASSESSMENT_METRIC_ID)
;
ALTER TABLE ASSESSMENT_RESULT ADD CONSTRAINT PK_ASSESSMENT_RESULT 
	PRIMARY KEY (ASSESSMENT_RESULT_ID)
;
ALTER TABLE CRITERIA ADD CONSTRAINT PK_CRITERIA 
	PRIMARY KEY (CRITERIA_ID)
;
ALTER TABLE DIMENSION ADD CONSTRAINT PK_DIMENSION 
	PRIMARY KEY (DIMENSION_ID)
;
ALTER TABLE DIMENSION_WEIGHTING ADD CONSTRAINT PK_DIMENSION_WEIGHTING 
	PRIMARY KEY (DIMENSION_WEIGHTING_ID)
;
ALTER TABLE LAYER ADD CONSTRAINT PK_LAYER 
	PRIMARY KEY (LAYER_ID)
;
ALTER TABLE LAYER2DIMENSION ADD CONSTRAINT PK_LAYER2DIMENSION 
	PRIMARY KEY (DIMENSION_ID, LAYER_ID)
;

--Foreingn keys
ALTER TABLE ASSESSMENT_HISTORY ADD CONSTRAINT FK_ASSESSHIST_ASSESSRESULT 
	FOREIGN KEY (ASSESSMENT_RESULT_ID) REFERENCES ASSESSMENT_RESULT (ASSESSMENT_RESULT_ID)
;
ALTER TABLE ASSESSMENT_METRIC ADD CONSTRAINT FK_CRITERIA_ID 
	FOREIGN KEY (CRITERIA_ID) REFERENCES CRITERIA (CRITERIA_ID)
;
ALTER TABLE ASSESSMENT_METRIC ADD CONSTRAINT FK_ASSESSMETRIC_LAYER2DIM 
	FOREIGN KEY (DIMENSION_ID, LAYER_ID) REFERENCES LAYER2DIMENSION (DIMENSION_ID, LAYER_ID)
;
ALTER TABLE ASSESSMENT_RESULT ADD CONSTRAINT FK_ASSESSMENT_METRIC_ID 
	FOREIGN KEY (ASSESSMENT_METRIC_ID) REFERENCES ASSESSMENT_METRIC (ASSESSMENT_METRIC_ID)
;
ALTER TABLE DIMENSION_WEIGHTING ADD CONSTRAINT FK_DIMWEIGHTING_LAYER2DIM 
	FOREIGN KEY (DIMENSION_ID, LAYER_ID) REFERENCES LAYER2DIMENSION (DIMENSION_ID, LAYER_ID)
;
ALTER TABLE LAYER2DIMENSION ADD CONSTRAINT FK_DIMENSION2DIMENSION_LAYER
	FOREIGN KEY (DIMENSION_ID) REFERENCES DIMENSION (DIMENSION_ID)
;
ALTER TABLE LAYER2DIMENSION ADD CONSTRAINT FK_LAYER2DIMENSION_LAYER 
	FOREIGN KEY (LAYER_ID) REFERENCES LAYER (LAYER_ID)
;

COMMIT;

---- Foreingn keys to dspace standard model
--ALTER TABLE ASSESSMENT_HISTORY ADD CONSTRAINT FK_ASSESSMENT_HISTORY_EPERSON FOREIGN KEY (EPERSON_ID) REFERENCES EPERSON (EPERSON_ID);
--ALTER TABLE ASSESSMENT_RESULT ADD CONSTRAINT FK_ASSESSMENT_RESULT_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID);
--ALTER TABLE DIMENSION_WEIGHTING ADD CONSTRAINT FK_DIMENSION_WEIGHTING_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID);
